services:
  dicom-anonymizer-web:
    build: .
    container_name: Dicom Anonymizer
    ports:
      - "5000:5000"
    volumes:
      # Mount directories for persistent storage (optional)
      - ./temp_uploads:/app/temp_uploads
      - ./temp_outputs:/app/temp_outputs
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - default

volumes:
  uploads_data:
  outputs_data: