services:
  dicom-anonymizer:
    build: .
    container_name: dicom-anonymizer
    # Uncomment for direct access testing
    # ports:
    #   - "5000:5000"
    labels:
        com.docker.compose.project: "docker"
        traefik.enable: "true"
        traefik.http.routers.dicom.tls.certresolver: "dns1"
        traefik.http.routers.dicom.rule: "Host(`SITE`)"
        traefik.http.routers.dicom.entrypoints: "http,https"
        traefik.http.routers.dicom.tls: "true"
        traefik.http.routers.dicom.middlewares: "secure-headers"
        traefik.http.services.dicom.loadbalancer.server.port: "5000"
        traefik.docker.network: "traefik_lan"
    volumes:
      # Mount directories for persistent storage (optional)
      - dicom_uploads:/app/temp_uploads
      - dicom_outputs:/app/temp_outputs
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - APP_PASSWORD=${APP_PASSWORD:-secure_password_here}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-fallback-secret-key}
      - SESSION_TIMEOUT_MINUTES=${SESSION_TIMEOUT_MINUTES:-60}
      # Brute force protection configuration
      - MAX_LOGIN_ATTEMPTS=${MAX_LOGIN_ATTEMPTS:-5}
      - LOGIN_LOCKOUT_DURATION=${LOGIN_LOCKOUT_DURATION:-300}
      - EXPONENTIAL_BACKOFF_BASE=${EXPONENTIAL_BACKOFF_BASE:-2}
      # Add additional Flask production settings
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    restart: unless-stopped
    networks:
      - default
      - traefik_lan
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  dicom_uploads:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=2G,noexec,nosuid,nodev
  dicom_outputs:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=2G,noexec,nosuid,nodev

networks:
  traefik_lan:
    external: true
