services:
  dicom-anonymizer-web:
    build: .
    container_name: dicom-anonymizer
    ports:
      - "5000:5000"
    volumes:
      # Mount directories for persistent storage (optional)
      - uploads_data:/app/temp_uploads:rw
      - outputs_data:/app/temp_outputs:rw
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - default

volumes:
  uploads_data:
    driver: local
  outputs_data:
    driver: local
