services:
  dicom-anonymizer:
    build: .
    container_name: ${CONTAINER_NAME:-Dicom-Anonymizer}
    labels:
        com.docker.compose.project: "${COMPOSE_PROJECT_NAME:-docker}"
    volumes:
      # Mount directories for persistent storage (optional)
      - dicom_uploads:/app/temp_uploads
      - dicom_outputs:/app/temp_outputs
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - FLASK_APP=${FLASK_APP:-app.py}
      - APP_PASSWORD=${APP_PASSWORD:-secure_password_here}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-fallback-secret-key}
      - SESSION_TIMEOUT_MINUTES=${SESSION_TIMEOUT_MINUTES:-60}
      # Brute force protection configuration
      - MAX_LOGIN_ATTEMPTS=${MAX_LOGIN_ATTEMPTS:-5}
      - LOGIN_LOCKOUT_DURATION=${LOGIN_LOCKOUT_DURATION:-300}
      - EXPONENTIAL_BACKOFF_BASE=${EXPONENTIAL_BACKOFF_BASE:-2}
      # Add additional Flask production settings
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED:-1}
      - PYTHONDONTWRITEBYTECODE=${PYTHONDONTWRITEBYTECODE:-1}
    restart: ${RESTART_POLICY:-unless-stopped}
    # Uncomment for direct access testing
    # ports:
    #   - "${APP_PORT:-5000}:5000"
    networks:
      - nginx_lan
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: ${HEALTH_CHECK_INTERVAL:-30s}
      timeout: ${HEALTH_CHECK_TIMEOUT:-10s}
      retries: ${HEALTH_CHECK_RETRIES:-3}
      start_period: ${HEALTH_CHECK_START_PERIOD:-40s}

volumes:
  dicom_uploads:
    driver: ${VOLUME_DRIVER:-local}
    driver_opts:
      type: ${VOLUME_TYPE:-tmpfs}
      device: ${VOLUME_DEVICE:-tmpfs}
      o: ${VOLUME_OPTIONS:-size=10G,noexec,nosuid,nodev}
  dicom_outputs:
    driver: ${VOLUME_DRIVER:-local}
    driver_opts:
      type: ${VOLUME_TYPE:-tmpfs}
      device: ${VOLUME_DEVICE:-tmpfs}
      o: ${VOLUME_OPTIONS:-size=10G,noexec,nosuid,nodev}

networks:
  nginx_lan:
    external: ${NGINX_NETWORK_EXTERNAL:-true}
